spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/udemy
    password: ''
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  doc:
    api-docs:
      path: /api-docs
server:
  port: '8080'

build:
  version: "3.0"
